Moex\CoreBundle\Entity\MeDrivers:
  type: entity
  repositoryClass: Moex\CoreBundle\Repository\MeDriversRepository
  table: me_drivers
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: IDENTITY
    driverName:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: driver_name
    motoNo:
      type: string
      length: 250
      fixed: false
      nullable: true 
      column: moto_no 
    driverAge:
      type: integer
      length: 2 
      nullable: true 
      column: driver_age 
    driverInfo:
      type: text
      nullable: true 
      column: driver_info
    phone:
      type: string
      length: 250
      fixed: false
      nullable: false
    position:
      type: string
      length: 250
      fixed: false
      nullable: false
    money:
      type: string
      length: 250
      default: "0"
      fixed: false
      nullable: true 
    lat:
      type: string
      length: 250
      fixed: false
      nullable: false
    lng:
      type: string
      length: 250
      fixed: false
      nullable: false
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  lifecycleCallbacks: {  }
