Moex\CoreBundle\Entity\MeDrivers:
  type: entity
  repositoryClass: Moex\CoreBundle\Repository\MeDriversRepository
  table: me_drivers
  id:
    id:
      type: bigint
      generator: { strategy: AUTO }
  fields:
    driverCode:
      type: string
      length: 250
      column: driver_code
    driverType:
      type: integer 
      lenght: 1
      column: driver_type
    driverName:
      type: string
      length: 250
      column: driver_name
    motoNo:
      type: string
      length: 250
      column: moto_no 
    driverAge:
      type: integer
      length: 2 
      column: driver_age 
    driverInfo:
      type: text
      nullable: true 
      column: driver_info
    phone:
      type: string
      length: 250
    position:
      type: string
      length: 250
    image:
      type: string
      length: 255
    money:
      type: string
      length: 250
      default: "0"
    moex_money:
      type: string
      length: 250
      default: "0"
    d_money:
      type: string
      length: 250
      default: "0"
    lat:
      type: string
      length: 250
    lng:
      type: string
      length: 250
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  oneToMany:
    driver_money:
      targetEntity: MeMoney 
      mappedBy: driver 
    driver_order:
      targetEntity: MeOrderDriver 
      mappedBy: driver 
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
