Moex\CoreBundle\Entity\MeMoney:
  type: entity
  repositoryClass: Moex\CoreBundle\Repository\MeMoneyRepository
  table: me_money
  id:
    id:
      type: bigint
      generator: { strategy: AUTO }
  fields:
    amount:
      type: string
      length: 250
      nullable: false
      column: amount
    description:
      type: text 
      nullable: true 
      column: description 
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  manyToOne:
    user:
      targetEntity: MeUsers 
      inversedBy: money 
      joinColumn:
        name: to_id 
        referencedColumnName: id
    driver:
      targetEntity: MeDrivers 
      inversedBy: driver_money
      joinColumn:
        name: from_id 
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
