Moex\CoreBundle\Entity\MeOrderDriver:
  type: entity
  repositoryClass: Moex\CoreBundle\Repository\MeOrderDriverRepository
  table: me_order_driver
  id:
    id:
      type: bigint
      generator: { strategy: IDENTITY }
  fields:
    money:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: money 
    driverMoney:
      type: string
      length: 250
      nullable: true
      column: driver_money
    roadMoney:
      type: string
      length: 250
      nullable: true
      column: road_money
    moexMoney:
      type: string
      length: 250
      nullable: true
      column: moex_money
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  oneToMany:
    orderdrivermeta:
      targetEntity: MeOrderDrivermeta
      mappedBy: ordermeta 
      cascade: [ persist ]
  manyToOne:
    order:
      targetEntity: MeOrders
      inversedBy: order_driver 
      joinColumn:
        name: order_id 
        referencedColumnName: id
    driver:
      targetEntity: MeDrivers 
      inversedBy: driver_money
      joinColumn:
        name: driver_id 
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
