Moex\CoreBundle\Entity\MeOrders:
  type: entity
  repositoryClass: Moex\CoreBundle\Repository\MeOrdersRepository
  table: me_orders
  id:
    id:
      type: bigint
      generator: { strategy: AUTO }
  fields:
    customerId:
      type: bigint
      nullable: false
      column: customer_id
    orderCode:
      type: string
      length: 250
      nullable: true 
      column: order_code
    serviceType:
      type: smallint
      nullable: false
      column: service_type
    thereturn:
      type: boolean 
      nullable: false
      column: thereturn 
    orderName:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: order_name
    orderFrom:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: order_from
    orderTo:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: order_to
    orderInfo:
      type: text
      nullable: false 
      column: order_info
    phone:
      type: string
      length: 250
      fixed: false
      nullable: false
    distance:
      type: string
      length: 250
      fixed: false
      nullable: true 
    extraPrice:
      type: string
      length: 250
      nullable: false
      column: extra_price 
    roadPrice:
      type: string
      length: 250
      column: road_price 
    price:
      type: string
      length: 250
      fixed: false
      nullable: false
    surcharge:
      type: string
      length: 250
      nullable: false
    promotion:
      type: string
      length: 250
      nullable: false
    orderStatus:
      type: string 
      length: 250
      nullable: false
      column: order_status 
    receiverName:
      type: string 
      length: 250
      nullable: true 
      column: receiver_name
    receiverPhone:
      type: string 
      length: 250
      nullable: true 
      column: receiver_phone
    receiverAddress:
      type: string 
      length: 250
      nullable: true 
      column: receiver_address 
    senderAddress:
      type: string 
      length: 250
      nullable: true 
      column: sender_address 
    lat:
      type: string
      length: 250
      fixed: false
      nullable: false
    lng:
      type: string
      length: 250
      fixed: false
      nullable: false
    startTime:
      type: datetime
      nullable: true 
      column: start_time 
    orderTime:
      type: datetime
      nullable: true 
      column: order_time 
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  oneToMany:
    order_driver:
      targetEntity: MeOrderDriver 
      mappedBy: order 
    ordermeta:
      targetEntity: MeOrdermeta
      mappedBy: order 
      cascade: [ persist ]
  manyToOne:
    user:
      targetEntity: MeUsers 
      inversedBy: order 
      joinColumn:
        name: user_id 
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
