Moex\CoreBundle\Entity\MeOrders:
  type: entity
  repositoryClass: Moex\CoreBundle\Repository\MeOrdersRepository
  table: me_orders
  id:
    id:
      type: bigint
      generator: { strategy: AUTO }
  fields:
#    userId:
#      type: bigint
#      nullable: false
#      column: user_id
    customerId:
      type: bigint
      nullable: false
      column: customer_id
    orderCode:
      type: string
      length: 250
      nullable: true 
      column: order_code
    serviceType:
      type: smallint
      nullable: false
      column: service_type
    orderName:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: order_name
    orderFrom:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: order_from
    orderTo:
      type: string
      length: 250
      fixed: false
      nullable: false
      column: order_to
    orderInfo:
      type: text
      nullable: false 
      column: order_info
    phone:
      type: string
      length: 250
      fixed: false
      nullable: false
    distance:
      type: string
      length: 250
      fixed: false
      nullable: true 
    price:
      type: string
      length: 250
      fixed: false
      nullable: false
    orderStatus:
      type: string 
      length: 250
      nullable: false
      column: order_status 
    lat:
      type: string
      length: 250
      fixed: false
      nullable: false
    lng:
      type: string
      length: 250
      fixed: false
      nullable: false
    startTime:
      type: datetime
      nullable: true 
      column: start_time 
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      column: updated_at
  oneToMany:
    order_driver:
      targetEntity: MeOrderDriver 
      mappedBy: order 
  manyToOne:
    user:
      targetEntity: MeUsers 
      inversedBy: order 
      joinColumn:
        name: user_id 
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
