Moex\CoreBundle\Entity\MeOrdermeta:
  type: entity
  repositoryClass: Moex\CoreBundle\Repository\MeOrdermetaRepository
  table: me_ordermeta
  id:
    id:
      type: bigint
      generator: { strategy: IDENTITY }
  fields:
    metaKey:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: meta_key
    metaValue:
      type: text
      nullable: true
      column: meta_value
  manyToOne:
    order:
      targetEntity: MeOrders 
      inversedBy: ordermeta 
      joinColumn:
        name: order_id 
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
