<?php
namespace Moex\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MeOrdermetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeOrdermetaRepository extends EntityRepository
{
}
