<?php
namespace Moex\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MeUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeUsersRepository extends EntityRepository
{

    public function findByFilterQuery(\Moex\CoreBundle\Entity\UserFilter $filter)
    {
        $query = $this->createQueryBuilder('u')
                              ->where('1 = 1');

        if ($filter->getUserLogin() != null) {
            $query = $query->andWhere('u.userLogin LIKE :userlogin')
                            ->setParameter('userlogin', "%".$filter->getUserLogin()."%");
        }

        if ($filter->getUserEmail() != null) {
            $query = $query->andWhere('u.userEmail LIKE :useremail')
                            ->setParameter('useremail', "%".$filter->getUserEmail()."%");
        }

		$query = $query->orderBy('u.id', 'DESC');

        return $query->getQuery();
    }
}
