parameters:
  moex.version: V1.0
  moex.pagesize.default: 10
  moex.driver.money.max: 1000000 
  moex.order.status.pending: PENDING 
  moex.order.status.assigned: ASSIGNED
  moex.order.status.done: DONE 
twig:
    globals:
        status_assigned: %moex.order.status.assigned% 
        status_done: %moex.order.status.done% 
        status_pending: %moex.order.status.pending% 
