MoexCoreBundle:
    resource: "@MoexCoreBundle/Controller/"
    type:     annotation
    prefix:   /
unauthorized:
    pattern: /unauthorized
    defaults: { _controller: MoexCoreBundle:Default:unauthorized }

api:
    pattern: /api
    type: rest
    defaults: { _controller: MoexCoreBundle:Api:index, _format:json }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
