MoexCoreBundle:
    resource: "@MoexCoreBundle/Controller/"
    type:     annotation
    prefix:   /
unauthorized:
    pattern: /unauthorized
    defaults: { _controller: MoexCoreBundle:Default:unauthorized }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
